apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-deployment
  labels:
    app: discovery-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service-container
        image: imrankhanin3/discovery-service:latest
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://host.docker.internal:8761/eureka/
      #serviceAccountName: jenkins-admin
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service-container
        image: imrankhanin3/gateway-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://host.docker.internal:8761/eureka/
        - name: LOGGING_LEVEL_ROOT
          value: INFO
      #serviceAccountName: jenkins-admin  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  labels:
    app: customer-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service-container
        image: imrankhanin3/customer-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://host.docker.internal:8761/eureka/
      #serviceAccountName: jenkins-admin
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: imrankhanin3/order-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://host.docker.internal:8761/eureka/
      #serviceAccountName: jenkins-admin

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
  selector:
    app: discovery-service
    
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: gateway-service
    
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  selector:
    app: customer-service
    
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  selector:
    app: order-service      