apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  selector:
    app: customer-service