apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service-container
        image: imrankhanin3/gateway-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://host.docker.internal:8761/eureka/