apiVersion: v1
kind: Service
metadata:
  name: spring-rest-service
  labels:
    app: spring-rest-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9999
    targetPort: 8080
  selector:
    app: spring-rest