apiVersion: v1
kind: Service
metadata:
  name: spring-rest-service
  labels:
    app: spring-rest-app
spec:
  #type: ClusterIP #Default
  selector:
    app: spring-rest
  ports:
  - name: http
    port: 9999
    targetPort: 8080