input {
  file {
    path    => "/my-log/spring.log"
    start_position => "beginning"
  }
}

output { 
elasticsearch {
    hosts => ["elasticsearch:9200"]
	index => "spring-%{+YYYY.MM.dd}" #It will be created as index in elasticsearch
  }
}