spring.application.name=customer-service
server.port=3001

#Logger
logging.level.root=INFO

eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/

#Resillience4j
#Rate limiting
resilience4j.ratelimiter.instances.getMessageRateLimit.limit-for-period=2
resilience4j.ratelimiter.instances.getMessageRateLimit.limit-refresh-period=5s
resilience4j.ratelimiter.instances.getMessageRateLimit.timeout-duration=0
#The above properties represent that only 2 requests are allowed in 5 seconds duration. 
#Also, there is no timeout duration which means after completion of 5 seconds, the user can send request again.

#Retry
resilience4j.retry.instances.getMessageForRetry.max-attempts=5
resilience4j.retry.instances.getMessageForRetry.wait-duration=2s
#resilience4j.retry.instances.getMessageForRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

#Circuit Breaker
resilience4j.circuitbreaker.instances.getMessageForCircuitBreaker.failure-rate-threshold=80
resilience4j.circuitbreaker.instances.getMessageForCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.getMessageForCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.getMessageForCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.getMessageForCircuitBreaker.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.getMessageForCircuitBreaker.permitted-number-of-calls-in-half-open-state=4
resilience4j.circuitbreaker.instances.getMessageForCircuitBreaker.wait-duration-in-open-state=1s

#Time limiter
resilience4j.timelimiter.instances.getMessageTL.timeout-duration=1ms
resilience4j.timelimiter.instances.getMessageTL.cancel-running-future=false