apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-deployment
  labels:
    app: discovery-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
      - name: discovery-service-container
        image: imrankhanin3/discovery-service:latest
        ports:
        - containerPort: 8761
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://host.docker.internal:8761/eureka/